
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 15;
  public static final int SLASH = 24;
  public static final int UMINUS = 46;
  public static final int PERIOD = 45;
  public static final int REM = 25;
  public static final int SEMI = 43;
  public static final int INT = 14;
  public static final int LSS = 29;
  public static final int MINUS = 22;
  public static final int AND = 33;
  public static final int RPAR = 38;
  public static final int OR = 34;
  public static final int COMMA = 44;
  public static final int CLASS = 3;
  public static final int INC = 35;
  public static final int GEQ = 32;
  public static final int PLUS = 21;
  public static final int ASSIGN = 26;
  public static final int IF = 7;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int GTR = 31;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int FLOATNUM = 20;
  public static final int NULL = 17;
  public static final int NUMBER = 19;
  public static final int NEQ = 28;
  public static final int BREAK = 10;
  public static final int IDENT = 18;
  public static final int VOID = 4;
  public static final int LBRACK = 39;
  public static final int TIMES = 23;
  public static final int LBRACE = 41;
  public static final int ELSE = 8;
  public static final int RBRACK = 40;
  public static final int READ = 13;
  public static final int FINAL = 5;
  public static final int WHILE = 9;
  public static final int EQL = 27;
  public static final int FLOAT = 16;
  public static final int RBRACE = 42;
  public static final int LEQ = 30;
  public static final int LPAR = 37;
  public static final int DEC = 36;
  public static final int PRINT = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "CLASS",
  "VOID",
  "FINAL",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "NEW",
  "PRINT",
  "READ",
  "INT",
  "CHAR",
  "FLOAT",
  "NULL",
  "IDENT",
  "NUMBER",
  "FLOATNUM",
  "PLUS",
  "MINUS",
  "TIMES",
  "SLASH",
  "REM",
  "ASSIGN",
  "EQL",
  "NEQ",
  "LSS",
  "LEQ",
  "GTR",
  "GEQ",
  "AND",
  "OR",
  "INC",
  "DEC",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMI",
  "COMMA",
  "PERIOD",
  "UMINUS"
  };
}

